### ISSUE TITLE
Player life with life bar.

### ISSUE THREAD

**Issue by br-it0** [heroiclabs/fishgame-godot#8]
Hello guys, studding the source code for a some time and trying one way to do that, with no sucess, any sugestion?
Just want put a life for player die and show life bar in sinc...

**Comment by dsnopek** [comment]
It shouldn't be hard to add a life bar and HP!

As a quick overview for how I'd do it:

1. Add an `hp` variable to `actors/Player.gd`
2. Change the `hurt` method in `actors/Player.gd` to deduct points from this variable
3. In `actors/player-states/Hurt.gd` change `_on_Timer_timeout()` to only switch to the "Dead" state when the players `hp` is zero, otherwise switch to some other normal state
4. Add a life bar somewhere (could be on `UILayer` in `Main.tscn`) and have the `hurt` method on `actors/Player.gd` also update that if the `player_controlled` variable is true

From a design perspective, that's not the only way to do it. For example, you could also show the life bar above/below the player sprites themselves, which could allow you to see your opponents hp too. That would also be pretty easy to do!
